FROM codeberg.org/forgejo/forgejo:14

LABEL org.opencontainers.image.source="https://github.com/jacobprall/render-open-forge"
LABEL org.opencontainers.image.description="render-open-forge: Forgejo instance"

COPY app.ini /etc/templates/app.ini

EXPOSE 3000
EXPOSE 22
