FROM codeberg.org/forgejo/forgejo:14

LABEL org.opencontainers.image.source="https://github.com/jacobprall/openforge"
LABEL org.opencontainers.image.description="openforge: Forgejo instance"

COPY app.ini /etc/templates/app.ini

EXPOSE 3000
EXPOSE 22
