import { defineConfig } from "drizzle-kit";

export default defineConfig({
  schema: "../../packages/db/schema.ts",
  out: "./lib/db/migrations",
  dialect: "postgresql",
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
  tablesFilter: [
    "users",
    "accounts",
    "verification_tokens",
    "invites",
    "sessions",
    "pr_events",
    "skill_cache",
    "chats",
    "chat_messages",
    "agent_runs",
    "ci_events",
    "sync_connections",
    "mirrors",
    "specs",
    "verification_results",
    "llm_api_keys",
    "user_preferences",
    "usage_events",
    "api_keys",
    "infra_specs",
    "infra_resources",
    "infra_actions",
    "infra_observations",
  ],
});
