#!/usr/bin/env bash
# Register the Forgejo Actions runner with the local Forgejo instance.
#
# Usage:
#   FORGEJO_URL=http://localhost:3000 \
#   FORGEJO_ADMIN_TOKEN=<admin-token> \
#   ./scripts/register-runner.sh
#
# The script creates a global registration token via the Forgejo admin API,
# then writes a runner configuration file that the `runner` docker-compose
# service can use on startup.

set -euo pipefail

FORGEJO_URL="${FORGEJO_URL:-http://localhost:3000}"
ADMIN_TOKEN="${FORGEJO_ADMIN_TOKEN:?Set FORGEJO_ADMIN_TOKEN to an admin API token}"
RUNNER_NAME="${RUNNER_NAME:-openforge-runner}"
LABELS="${RUNNER_LABELS:-ubuntu-latest:docker://node:20,ubuntu-22.04:docker://ubuntu:22.04}"

echo "==> Requesting registration token from ${FORGEJO_URL}…"

REG_TOKEN=$(curl -sf \
  -H "Authorization: token ${ADMIN_TOKEN}" \
  -H "Content-Type: application/json" \
  "${FORGEJO_URL}/api/v1/admin/runners/registration-token" | \
  python3 -c "import sys,json; print(json.load(sys.stdin).get('token',''))" 2>/dev/null || true)

if [ -z "${REG_TOKEN}" ]; then
  echo "==> Admin endpoint unavailable; trying org-level…"
  REG_TOKEN=$(curl -sf \
    -H "Authorization: token ${ADMIN_TOKEN}" \
    -X POST \
    "${FORGEJO_URL}/api/v1/user/actions/runners/registration-token" | \
    python3 -c "import sys,json; print(json.load(sys.stdin).get('token',''))" 2>/dev/null || true)
fi

if [ -z "${REG_TOKEN}" ]; then
  echo "ERROR: Could not obtain registration token. Check FORGEJO_ADMIN_TOKEN and Forgejo version." >&2
  exit 1
fi

echo "==> Registration token: ${REG_TOKEN:0:6}…"

CONFIG_DIR="${RUNNER_DATA_DIR:-./runner-data}"
mkdir -p "${CONFIG_DIR}"

cat > "${CONFIG_DIR}/.runner" <<EOF
{
  "WARNING": "This file is auto-generated by register-runner.sh",
  "name": "${RUNNER_NAME}",
  "token": "${REG_TOKEN}",
  "address": "${FORGEJO_URL}",
  "labels": ["${LABELS//,/\",\"}"]
}
EOF

echo "==> Runner config written to ${CONFIG_DIR}/.runner"
echo "==> Start the runner: docker compose up runner"
